import jsPDF from 'jspdf';
import crypto from 'crypto';
import { format } from 'date-fns';
import type { AuditTrail } from '@shared/schema';

// AUDIT_SIGNING_KEY must be set via environment variable at startup (see server/index.ts).
// This module reads it at call time so it picks up the auto-generated key if the env var
// was not set before server startup.
function getSigningKey(): string {
  const key = process.env.AUDIT_SIGNING_KEY;
  if (!key) {
    throw new Error(
      'AUDIT_SIGNING_KEY environment variable is not set. ' +
      'Server startup should have generated one — check server/index.ts initialization.'
    );
  }
  return key;
}

interface SignatureData {
  timestamp: string;
  recordCount: number;
  dataHash: string;
  signature: string;
  version: string;
}

interface ExportMetadata {
  generatedAt: string;
  generatedBy: string;
  filters: {
    caseId?: string;
    eventType?: string;
    startDate?: string;
    endDate?: string;
  };
  recordCount: number;
  firmName?: string;
}

function generateDataHash(auditLogs: AuditTrail[]): string {
  const dataString = auditLogs.map(log => 
    `${log.id}|${log.timestamp}|${log.eventType}|${log.userId}|${log.caseId || ''}|${log.severity}`
  ).join('||');
  
  return crypto.createHash('sha256').update(dataString).digest('hex');
}

function generateSignature(dataHash: string, timestamp: string): string {
  const payload = `${dataHash}|${timestamp}|legalnote-audit-v1`;
  return crypto.createHmac('sha256', getSigningKey()).update(payload).digest('hex');
}

export function verifyAuditExportSignature(
  auditLogs: AuditTrail[],
  signatureData: SignatureData
): boolean {
  const dataHash = generateDataHash(auditLogs);
  const expectedSignature = generateSignature(dataHash, signatureData.timestamp);
  return signatureData.signature === expectedSignature && signatureData.dataHash === dataHash;
}

const EVENT_LABELS: Record<string, string> = {
  case_viewed: "Case Viewed",
  case_created: "Case Created",
  case_updated: "Case Updated",
  recording_started: "Recording Started",
  consent_given: "Consent Given",
  consent_declined: "Consent Declined",
  audio_uploaded: "Audio Uploaded",
  audio_playback_started: "Audio Playback Started",
  audio_deleted: "Audio Deleted",
  document_viewed: "Document Viewed",
  document_created: "Document Created",
  document_updated: "Document Updated",
  document_deleted: "Document Deleted",
  document_downloaded: "Document Downloaded",
  document_sent: "Document Sent",
  transcript_viewed: "Transcript Viewed",
  transcript_redacted: "Transcript Redacted",
  audit_exported_csv: "Audit Exported (CSV)",
  audit_exported_pdf: "Audit Exported (PDF)",
  calendar_connected: "Calendar Connected",
  calendar_disconnected: "Calendar Disconnected",
  calendar_synced: "Calendar Synced",
};

export function generateSignedAuditPDF(
  auditLogs: AuditTrail[],
  metadata: ExportMetadata
): Buffer {
  const pdf = new jsPDF('p', 'mm', 'a4');
  const pageWidth = pdf.internal.pageSize.getWidth();
  const pageHeight = pdf.internal.pageSize.getHeight();
  const margin = 15;
  const contentWidth = pageWidth - (margin * 2);
  let yPos = margin;

  const signatureTimestamp = new Date().toISOString();
  const dataHash = generateDataHash(auditLogs);
  const signature = generateSignature(dataHash, signatureTimestamp);

  const signatureData: SignatureData = {
    timestamp: signatureTimestamp,
    recordCount: auditLogs.length,
    dataHash,
    signature,
    version: 'legalnote-audit-v1',
  };

  pdf.setFillColor(0, 0, 0);
  pdf.rect(0, 0, pageWidth, 45, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(20);
  pdf.setFont('helvetica', 'bold');
  pdf.text(metadata.firmName || 'LegalNote', margin, 20);

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'normal');
  pdf.text('AUDIT TRAIL EXPORT', margin, 30);

  pdf.setFontSize(8);
  pdf.text(`Generated: ${format(new Date(metadata.generatedAt), "dd MMMM yyyy 'at' HH:mm:ss")}`, margin, 38);

  yPos = 55;

  pdf.setFillColor(34, 197, 94);
  pdf.rect(margin, yPos, contentWidth, 25, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.text('DIGITALLY SIGNED & VERIFIED', margin + 5, yPos + 8);

  pdf.setFontSize(7);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Signature: ${signature.substring(0, 32)}...`, margin + 5, yPos + 15);
  pdf.text(`Hash: SHA-256 | Records: ${auditLogs.length} | Version: ${signatureData.version}`, margin + 5, yPos + 21);

  yPos += 35;

  pdf.setTextColor(0, 0, 0);
  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Export Information', margin, yPos);

  yPos += 8;
  pdf.setFontSize(9);
  pdf.setFont('helvetica', 'normal');

  const exportInfo = [
    ['Generated By:', metadata.generatedBy],
    ['Export Date:', format(new Date(metadata.generatedAt), 'dd/MM/yyyy HH:mm:ss')],
    ['Total Records:', metadata.recordCount.toString()],
  ];

  if (metadata.filters.caseId) {
    exportInfo.push(['Case Filter:', metadata.filters.caseId]);
  }
  if (metadata.filters.eventType) {
    exportInfo.push(['Event Filter:', metadata.filters.eventType]);
  }

  exportInfo.forEach(([label, value]) => {
    pdf.setFont('helvetica', 'bold');
    pdf.text(label, margin, yPos);
    pdf.setFont('helvetica', 'normal');
    pdf.text(value, margin + 35, yPos);
    yPos += 5;
  });

  yPos += 10;

  pdf.setFontSize(12);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Audit Records', margin, yPos);
  yPos += 8;

  pdf.setFontSize(7);
  pdf.setFont('helvetica', 'bold');

  const colWidths = [35, 45, 30, 30, 40];
  const headers = ['Timestamp', 'Event Type', 'User ID', 'Severity', 'Case ID'];

  pdf.setFillColor(240, 240, 240);
  pdf.rect(margin, yPos - 4, contentWidth, 7, 'F');

  let xPos = margin;
  headers.forEach((header, i) => {
    pdf.text(header, xPos + 1, yPos);
    xPos += colWidths[i];
  });

  yPos += 6;

  pdf.setFont('helvetica', 'normal');
  pdf.setFontSize(6);

  auditLogs.forEach((log, index) => {
    if (yPos > pageHeight - 40) {
      pdf.addPage();
      yPos = margin;

      pdf.setFillColor(240, 240, 240);
      pdf.rect(margin, yPos - 4, contentWidth, 7, 'F');

      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(7);
      let headerX = margin;
      headers.forEach((header, i) => {
        pdf.text(header, headerX + 1, yPos);
        headerX += colWidths[i];
      });
      yPos += 6;
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(6);
    }

    if (index % 2 === 1) {
      pdf.setFillColor(250, 250, 250);
      pdf.rect(margin, yPos - 3, contentWidth, 5, 'F');
    }

    const row = [
      format(new Date(log.timestamp), 'dd/MM/yy HH:mm:ss'),
      EVENT_LABELS[log.eventType] || log.eventType,
      log.userId.substring(0, 10) + '...',
      log.severity,
      log.caseId ? log.caseId.substring(0, 12) + '...' : 'N/A',
    ];

    let rowX = margin;
    row.forEach((cell, i) => {
      const truncatedCell = cell.length > colWidths[i] / 2 ? cell.substring(0, Math.floor(colWidths[i] / 2) - 2) + '...' : cell;
      pdf.text(truncatedCell, rowX + 1, yPos);
      rowX += colWidths[i];
    });

    yPos += 5;
  });

  yPos += 15;

  if (yPos > pageHeight - 60) {
    pdf.addPage();
    yPos = margin;
  }

  pdf.setFillColor(59, 130, 246);
  pdf.rect(margin, yPos, contentWidth, 50, 'F');

  pdf.setTextColor(255, 255, 255);
  pdf.setFontSize(10);
  pdf.setFont('helvetica', 'bold');
  pdf.text('Cryptographic Signature Details', margin + 5, yPos + 10);

  pdf.setFontSize(7);
  pdf.setFont('helvetica', 'normal');
  pdf.text(`Signature Algorithm: HMAC-SHA256`, margin + 5, yPos + 18);
  pdf.text(`Data Hash (SHA-256): ${dataHash}`, margin + 5, yPos + 24);
  pdf.text(`Signature: ${signature}`, margin + 5, yPos + 30);
  pdf.text(`Timestamp: ${signatureTimestamp}`, margin + 5, yPos + 36);
  pdf.text(`Version: ${signatureData.version}`, margin + 5, yPos + 42);

  const pageCount = pdf.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    pdf.setPage(i);
    pdf.setTextColor(128, 128, 128);
    pdf.setFontSize(8);
    pdf.text(
      `Page ${i} of ${pageCount} | This document is digitally signed and tamper-evident`,
      pageWidth / 2,
      pageHeight - 10,
      { align: 'center' }
    );
  }

  return Buffer.from(pdf.output('arraybuffer'));
}
